<a href="https://colab.research.google.com/github/TieuDiem/Sobel-Operator/blob/main/Sobel_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ex1.**Sobel**

<strong>Convolution Formula: </strong> $G_{x \: or \: y} = F * I(x, y) = \sum_{j=-N}^{N} \sum_{i=-N}^{N} F(i, j)I(x-i, y-j)$


---

<strong>Step 0</strong>

*   $G_{x \: or \: y} \: tại \: x=0,y=0: \: F(-1,-1)I(1,1) + F(-1,0)I(1,0) + F(-1,1)I(1,-1)  +  F(0,-1)I(0,1) + F(0,0)I(0,0) + F(0,1)I(0,-1)  +   F(1,-1)I(-1,1) + F(1,0)I(-1,0) + F(1,1)I(-1,-1) = k1*p8 + k2*p7 + k3*p7 + k4*p2 + k5*p1 + k6*p1 + k7*p2 + k8*p1 + k9*p1$
*   $G_{x \: or \: y} \: tại \: x=1,y=0: \: F(-1,-1)I(2,1) + F(-1,0)I(2,0) + F(-1,1)I(2,-1)  +  F(0,-1)I(1,1) + F(0,0)I(1,0) + F(0,1)I(1,-1)  +   F(1,-1)I(0,1) + F(1,0)I(0,0) + F(1,1)I(0,-1) = k1*p9 + k2*p8 + k3*p7 + k4*p3 + k5*p2 + k6*p1 + k7*p3 + k8*p2 + k9*p1 $
*   $G_{x \: or \: y} \: tại \: x=2,y=0: \: F(-1,-1)I(3,1) + F(-1,0)I(3,0) + F(-1,1)I(3,-1)  +  F(0,-1)I(2,1) + F(0,0)I(2,0) + F(0,1)I(2,-1)  +   F(1,-1)I(1,1) + F(1,0)I(1,0) + F(1,1)I(1,-1) = k1*p10 + k2*p9 + k3*p8 + k4*p4 + k5*p3 + k6*p2 + k7*p4 + k8*p3 + k9*p2 $
*   $G_{x \: or \: y} \: tại \: x=3,y=0: \: F(-1,-1)I(4,1) + F(-1,0)I(4,0) + F(-1,1)I(4,-1)  +  F(0,-1)I(3,1) + F(0,0)I(3,0) + F(0,1)I(3,-1)  +   F(1,-1)I(2,1) + F(1,0)I(2,0) + F(1,1)I(2,-1) = k1*p11 + k2*p10 + k3*p9 + k4*p5 + k5*p4 + k6*p3 + k7*p5 + k8*p4 + k9*p3 $
*   $G_{x \: or \: y} \: tại \: x=4,y=0: \: F(-1,-1)I(5,1) + F(-1,0)I(5,0) + F(-1,1)I(5,-1)  +  F(0,-1)I(4,1) + F(0,0)I(4,0) + F(0,1)I(4,-1)  +   F(1,-1)I(3,1) + F(1,0)I(3,0) + F(1,1)I(3,-1) = k1*p12 + k2*p11 + k3*p10 + k4*p6 + k5*p5 + k6*p4 + k7*p6 + k8*p5 + k9*p4 $
*   $G_{x \: or \: y} \: tại \: x=5,y=0: \: F(-1,-1)I(6,1) + F(-1,0)I(6,0) + F(-1,1)I(6,-1)  +  F(0,-1)I(5,1) + F(0,0)I(5,0) + F(0,1)I(5,-1)  +   F(1,-1)I(4,1) + F(1,0)I(4,0) + F(1,1)I(4,-1) = k1*p12 + k2*p12 + k3*p11 + k4*p6 + k5*p6 + k6*p5 + k7*p6 + k8*p6 + k9*p5 $
<br>

*   $G_{x \: or \: y} \: tại \: x=0,y=1: \: F(-1,-1)I(1,2) + F(-1,0)I(1,1) + F(-1,1)I(1,0)  +  F(0,-1)I(0,2) + F(0,0)I(0,1) + F(0,1)I(0,0)  +   F(1,-1)I(-1,2) + F(1,0)I(-1,1) + F(1,1)I(-1,0) = k1*p14 + k2*p13 + k3*p13 + k4*p8 + k5*p7 + k6*p7 + k7*p2 + k8*p1 + k9*p1$
*   $G_{x \: or \: y} \: tại \: x=1,y=1: \: F(-1,-1)I(2,2) + F(-1,0)I(2,1) + F(-1,1)I(2,0)  +  F(0,-1)I(1,2) + F(0,0)I(1,1) + F(0,1)I(1,0)  +   F(1,-1)I(0,2) + F(1,0)I(0,1) + F(1,1)I(0,0) = k1*p15 + k2*p14 + k3*p13 + k4*p9 + k5*p8 + k6*p7 + k7*p3 + k8*p2 + k9*p1 $
*   $G_{x \: or \: y} \: tại \: x=2,y=1: \: F(-1,-1)I(3,2) + F(-1,0)I(3,1) + F(-1,1)I(3,0)  +  F(0,-1)I(2,2) + F(0,0)I(2,1) + F(0,1)I(2,0)  +   F(1,-1)I(1,2) + F(1,0)I(1,1) + F(1,1)I(1,0) = k1*p16 + k2*p15 + k3*p14 + k4*p10 + k5*p9 + k6*p8 + k7*p4 + k8*p3 + k9*p2 $
*   $G_{x \: or \: y} \: tại \: x=3,y=1: \: F(-1,-1)I(4,2) + F(-1,0)I(4,1) + F(-1,1)I(4,0)  +  F(0,-1)I(3,2) + F(0,0)I(3,1) + F(0,1)I(3,0)  +   F(1,-1)I(2,2) + F(1,0)I(2,1) + F(1,1)I(2,0) = k1*p17 + k2*p16 + k3*p15 + k4*p11 + k5*p10 + k6*p9 + k7*p5 + k8*p4 + k9*p3 $
*   $G_{x \: or \: y} \: tại \: x=4,y=1: \: F(-1,-1)I(5,2) + F(-1,0)I(5,1) + F(-1,1)I(5,0)  +  F(0,-1)I(4,2) + F(0,0)I(4,1) + F(0,1)I(4,0)  +   F(1,-1)I(3,2) + F(1,0)I(3,1) + F(1,1)I(3,0) = k1*p18 + k2*p17 + k3*p16 + k4*p12 + k5*p11 + k6*p10 + k7*p6 + k8*p5 + k9*p4 $
*   $G_{x \: or \: y} \: tại \: x=5,y=1: \: F(-1,-1)I(6,2) + F(-1,0)I(6,1) + F(-1,1)I(6,0)  +  F(0,-1)I(5,2) + F(0,0)I(5,1) + F(0,1)I(5,0)  +   F(1,-1)I(4,2) + F(1,0)I(4,1) + F(1,1)I(4,0) = k1*p18 + k2*p17 + k3*p17 + k4*p12 + k5*p12 + k6*p11 + k7*p6 + k8*p6 + k9*p5 $

<strong>Step 1</strong>
*   $G_{x } \: tại \: x=0,y=0: \: -11 + 0 + 8 - 10 + 0 + 8 - 5 + 0 + 4 = -6$
*   $G_{x} \: tại \: x=0,y=1: \: -14+0+12-22+0+16-5+0+4=-9$
*   $G_{x} \: tại \: x=0,y=2: \: -19+0+21-28+0+24-11+0+8=-5$
*   $G_{x} \: tại \: x=0,y=3: \: -26+0+28-38+0+42-14+0+12=4$
*   $G_{x} \: tại \: x=0,y=4: \: -32+0+34-52+0+56-19+0+21=8$
*   $G_{x} \: tại \: x=0,y=5: \: -32+0+34-64+0+68-26+0+28=8$

<strong>Step 2</strong>
*   $G_{y} \: tại \: x=0,y=0: \:11+16+8+0+0+0-4-8-5=18$
*   $G_{y} \: tại \: x=0,y=1: \:14+24+12+0+0+0-5-8-4=33$
*   $G_{y} \: tại \: x=0,y=2: \:19+42+21+0+0+0-11-16-8=47$
*   $G_{y} \: tại \: x=0,y=3: \:26+56+28+0+0+0-14-24-12=60$
*   $G_{y} \: tại \: x=0,y=4: \:32+68+34+0+0+0-19-42-21=52$
*   $G_{y} \: tại \: x=0,y=5: \:32+68+34+0+0+0-26-56-28=24$

<strong>Step 3</strong>
*   $G \: tại \: x=0,y=0: \: |-6| + |18| = 24$
*   $G \: tại \: x=0,y=1: \: |-9| + |33| = 42$
*   $G \: tại \: x=0,y=2: \: |-5| + |47| = 52$
*   $G \: tại \: x=0,y=3: \: |4| + |60| = 64$
*   $G \: tại \: x=0,y=4: \: |8| + |18| = 26$
*   $G \: tại \: x=0,y=5: \: |8| + |18| = 26$

In [ ]:
import numpy as np
from scipy.signal import convolve2d

In [ ]:
'# Step 4'
K_x = np.array([[-1, 0, 1],
                [-2, 0, 2],
                [-1, 0, 1]])


'# Step 5'
K_y = np.array([[1, 2, 1],
                [0, 0, 0],
                [-1, -2, -1]])


In [ ]:
M = np . array ([[ 4 , 5 , 2 , 4 , 8 , 5 ,] ,
                 [ 8 , 11 , 8 , 11 , 12 , 13] ,
                 [12 , 14 , 17 , 16 , 16 , 20] ,
                 [21 , 19 , 21 , 23 , 25 , 25] ,
                 [28 , 26 , 29 , 30 , 30 , 32] ,
                 [34 , 32 , 32 , 33 , 38 , 36]])

In [ ]:
G_x = convolve2d(M, K_x, mode='same', boundary='symm')
print(G_x)

[[ -6   6   3 -22  -5   8]
 [ -9  -3  -1 -13  -9  -3]
 [ -5 -10  -8  -6 -12  -9]
 [  4  -6 -14  -8 -10  -6]
 [  8   0 -13 -12  -9  -2]
 [  8   5  -7 -19 -11   4]]


In [ ]:
G_y = convolve2d(M, K_y, mode='same', boundary='symm')
print(G_y)

[[18 22 25 24 23 28]
 [33 41 51 47 43 53]
 [47 42 46 50 50 49]
 [60 52 50 54 54 50]
 [52 50 45 44 47 46]
 [24 21 15 17 23 20]]


In [ ]:
# Step 7
def compute_sobel_edges(matrix,mode="sum"):
    K_x = np.array([[-1, 0, 1],
                [-2, 0, 2],
                [-1, 0, 1]])

    K_y = np.array([[1, 2, 1],
                    [0, 0, 0],
                    [-1, -2, -1]])

    G_x = convolve2d(matrix, K_x, mode='same', boundary='symm')
    G_y = convolve2d(matrix, K_y, mode='same', boundary='symm')
    if mode =="sum":
      G = np.abs(G_x) + np.abs(G_y)
    elif  mode =="thin_sum": 
      pass     
    return G
G = compute_sobel_edges(matrix=M)
print(G)

[[24 28 28 46 28 36]
 [42 44 52 60 52 56]
 [52 52 54 56 62 58]
 [64 58 64 62 64 56]
 [60 50 58 56 56 48]
 [32 26 22 36 34 24]]


#Ex2.**Simple Optimization**

In [ ]:
import numpy as np
def find_minimum(f, min_value, num_iteration, step):
    delta_x = 1e-6
    for i in range(num_iteration):
        dx = (f(min_value + delta_x / 2) - f(min_value - delta_x/2)) / delta_x
        dx_sign = np.sign(dx)
        if dx_sign == 0:
            break
        else:
            min_value = min_value - dx_sign*step
        print(f'[INFO] Iterattion ({i+1}/{num_iteration}): New x = {min_value}')
    return min_value

In [ ]:
import random
def f(x):
    return 3*x**4 - 4*x**2 - 6*x - 3

x = random.uniform(-10, 10)
print('Initial x: ', x)

min_value = find_minimum(f=f, min_value=x, num_iteration=2000, step=0.01)
print(min_value)

Initial x:  -4.7398385759716
[INFO] Iterattion (1/2000): New x = -4.7298385759716
[INFO] Iterattion (2/2000): New x = -4.7198385759716
[INFO] Iterattion (3/2000): New x = -4.709838575971601
[INFO] Iterattion (4/2000): New x = -4.699838575971601
[INFO] Iterattion (5/2000): New x = -4.689838575971601
[INFO] Iterattion (6/2000): New x = -4.679838575971601
[INFO] Iterattion (7/2000): New x = -4.6698385759716015
[INFO] Iterattion (8/2000): New x = -4.659838575971602
[INFO] Iterattion (9/2000): New x = -4.649838575971602
[INFO] Iterattion (10/2000): New x = -4.639838575971602
[INFO] Iterattion (11/2000): New x = -4.629838575971602
[INFO] Iterattion (12/2000): New x = -4.6198385759716025
[INFO] Iterattion (13/2000): New x = -4.609838575971603
[INFO] Iterattion (14/2000): New x = -4.599838575971603
[INFO] Iterattion (15/2000): New x = -4.589838575971603
[INFO] Iterattion (16/2000): New x = -4.579838575971603
[INFO] Iterattion (17/2000): New x = -4.569838575971604
[INFO] Iterattion (18/2000): N

##2.2.
* $f(x)=3x^4-4x^2-6x-3$,&ensp; num iteration=5, step=0.1, $x$ khởi tạo lần  đầu tiên bằng 3.0
* $f'(x)=12x^3 - 8x -6$
* **Lần đầu tiên**
    * $dx = 12x^3 - 8x -6 = 12*(3.0)^3 - 8 * (3.0) -6=294$
    * $dx >0, x=x-step=3-0.1=2.9$
* **Lần thứ 2**
    * $dx = 12x^3 - 8x -6 = 12*(2.9)^3 - 8 * (2.9) -6=263.468$
    * $dx >0, x=x-step=2.9-0.1=2.8$
* **Lần thứ 3**
    * $dx = 12x^3 - 8x -6 = 12*(2.8)^3 - 8 * (2.8) -6=235.024$
    * $dx >0, x=x-step=2.8-0.1=2.7$
* **Lần thứ 4**
    * $dx = 12x^3 - 8x -6 = 12*(2.7)^3 - 8 * (2.7) -6=208.596$
    * $dx >0, x=x-step=2.7-0.1=2.6$
* **Lần thứ 5**
    * $dx = 12x^3 - 8x -6 = 12*(2.6)^3 - 8 * (2.6) -6=184.112$
    * $dx >0, x=x-step=2.6-0.1=2.5$


In [ ]:
import random

def f(x):
    return 3*x**4 - 4*x**2 - 6*x - 3

x = 3.0
print('Initial x: ', x)

min_valuex = find_minimum(f=f, min_value=x, num_iteration=5, step=0.1)

Initial x:  3.0
[INFO] Iterattion (1/5): New x = 2.9
[INFO] Iterattion (2/5): New x = 2.8
[INFO] Iterattion (3/5): New x = 2.6999999999999997
[INFO] Iterattion (4/5): New x = 2.5999999999999996
[INFO] Iterattion (5/5): New x = 2.4999999999999996


#Ex3.**Simple Optimization (Chain Rule)**

##3.1.**Find minimum function**

In [ ]:
def find_minimum(f, g, min_value, num_iteration, step):
    delta_x = 1e-6
    delta_f = 1e-6
    for _ in range(num_iteration):
        df_dx = (f(min_value + delta_x/2) - f(min_value - delta_x/2)) / delta_x
        fx = f(min_value)
        dg_df = (g(fx + delta_f / 2) - g(fx - delta_f / 2)) / delta_f
        dg_dx = dg_df * df_dx
        dg_dx_sign = np.sign(dg_dx)

        if dg_dx_sign == 0:
            break
        else:
            min_value = min_value - dg_dx_sign*step
    return min_value

In [ ]:
import random
def f(x):
    return 2* x **3 - 3* x **2 + 4* x

def g(x):
    return x **2 - 10* x + 2

x = random . uniform ( -2 , 2)
print (" initial x: ", x )

min_value = find_minimum (f =f , g=g , min_value=x , num_iteration=40 , step=0.1)
print (min_value)

 initial x:  0.060860755098468555
1.460860755098469


##3.2.**Simple optimization algorithm**

* $f(x)=2x^3-3x^2+4x, \: g(x)=x^2-10x+2$, &ensp; num_iteration=5, step=0.1, $x$ khởi tạo đầu tiên bằng -1.5
* $f'(x)=6x^2-6x+4,\: g'(x)=2x-10, \: g'(x)=g'(f(x)) * f'(x)$
* **Lần đầu tiên**
    * $f(-1.5) = 2 * (-1.5)^3 - 3 * (-1.5)^2 + 4 * (-1.5)=-19.5$
    * $df \\_ dx =6x^2-6x+4=6 * (-1.5)^2-6 * (-1.5) +4 = 26.5$
    * $dg \\_ df = 2 * f(x)-10= 2 * f(-1.5)-10= 2 * (-19.5) - 10=-49$
    * $dg \\_ dx = dg \\_ df * df \\_ dx = (-49) * (26.5) = -1298.5$
    * $dx \\_ dg < 0, \: x = x+step=-1.5+0.1=-1.4$

* **Lần thứ 2**
    * $f(-1.4) = 2 * (-1.4)^3 - 3 * (-1.4)^2 + 4 * (-1.4)=-16.97$
    * $df \\_ dx =6x^2-6x+4=6 * (-1.4)^2-6 * (-1.4) +4 = 24.16$
    * $dg \\_ df = 2 * f(x)-10= 2 * f(-1.4)-10= 2 * (-16.97) - 10=-43.94$
    * $dg \\_ dx = dg \\_ df * df \\_ dx = (-43.94) * (24.16) = -1061.49$
    * $dx \\_ dg < 0, \: x = x-step=-1.4+0.1=-1.3$

* **Lần thứ 3**
    * $f(-1.3) = 2 * (-1.3)^3 - 3 * (-1.3)^2 + 4 * (-1.3)=-14.66$
    * $df \\_ dx =6x^2-6x+4=6 * (-1.3)^2-6 * (-1.3) +4 = 21.94$
    * $dg \\_ df = 2 * f(x)-10= 2 * f(-1.3)-10= 2 * (-14.66) - 10=-39.33$
    * $dg \\_ dx = dg \\_ df * df \\_ dx = (-39.33) * (21.94) = -862.86$
    * $dx \\_ dg < 0, \: x = x-step=-1.3+0.1=-1.2$

* **Lần thứ 4**
    * $f(-1.2) = 2 * (-1.2)^3 - 3 * (-1.2)^2 + 4 * (-1.2)=-12.58$
    * $df \\_ dx =6x^2-6x+4=6 * (-1.2)^2-6 * (-1.2) +4 = 19.84$
    * $dg \\_ df = 2 * f(x)-10= 2 * f(-1.2)-10= 2 * (-12.58) - 10=-35.15$
    * $dg \\_ dx = dg \\_ df * df \\_ dx = (-35.15) * (19.84) = -697.41$
    * $dx \\_ dg < 0, \: x = x-step=-1.2+0.1=-1.1$

 -10.69 17.86 -31.38 -560.51
* **Lần thứ 5**
    * $f(-1.1) = 2 * (-1.1)^3 - 3 * (-1.1)^2 + 4 * (-1.1)=-10.69$
    * $df \\_ dx =6x^2-6x+4=6 * (-1.9)^2-6 * (-1.9) +4 = 17.86$
    * $dg \\_ df = 2 * f(x)-10= 2 * f(-1.9)-10= 2 * (-10.69) - 10=-31.38$
    * $dg \\_ dx = dg \\_ df * df \\_ dx = (-31.38) * (17.86) = -560.51$
    * $dx \\_ dg < 0, \: x = x-step=-1.1+0.1=-1.0$

In [ ]:
import random

def f(x):
    return 2* x **3 - 3* x **2 + 4* x

def g(x):
    return x **2 - 10* x + 2

x = -1.5
print (" initial x: ", x )

x = find_minimum (f =f , g=g , min_value=x , num_iteration=5 , step=0.1)

 initial x:  -1.5
